[package]
name = "collided"
version = "0.1.0"
edition = "2024"

[lib]
name = "collide"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true
proc-macro = false
harness = true
crate-type = ["lib"]
required-features = []

[dependencies]
